### ISSUE TITLE
Cannot run MELD/teacher.py because 'Could not find image processor class in the image processor config or the model config.'

### ISSUE THREAD

**Issue by guoxun77** [yuntaeyang/TelME#7]
I ran the MELD/teacher.py and the results are as follows:

Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
True
D:\3090x8\experiment\TelME-main
###Save Path###  ./MELD/save_model
Some weights of the model checkpoint at roberta-large were not used when initializing RobertaModel: ['lm_head.bias', 'lm_head.layer_norm.bias', 'lm_head.dense.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|          | 0/10 [00:00<?, ?it/s]Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
  0%|          | 0/10 [01:31<?, ?it/s]
Traceback (most recent call last):
  File "D:\3090x8\experiment\TelME-main\MELD\teacher.py", line 170, in <module>
    main(args)
  File "D:\3090x8\experiment\TelME-main\MELD\teacher.py", line 160, in main
    model_train(training_epochs, model, train_loader, dev_loader, test_loader, optimizer, scheduler, max_grad_norm, save_path)
  File "D:\3090x8\experiment\TelME-main\MELD\teacher.py", line 67, in model_train
    optimizer.step()
  File "D:\anaconda\envs\pyth\Lib\site-packages\torch\optim\lr_scheduler.py", line 137, in wrapper
    return func.__get__(opt, opt.__class__)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\pyth\Lib\site-packages\torch\optim\optimizer.py", line 487, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\pyth\Lib\site-packages\torch\optim\optimizer.py", line 91, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\pyth\Lib\site-packages\torch\optim\adamw.py", line 220, in step
    adamw(
  File "D:\anaconda\envs\pyth\Lib\site-packages\torch\optim\optimizer.py", line 154, in maybe_fallback
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\pyth\Lib\site-packages\torch\optim\adamw.py", line 782, in adamw
    func(
  File "D:\anaconda\envs\pyth\Lib\site-packages\torch\optim\adamw.py", line 606, in _multi_tensor_adamw
    exp_avg_sq_sqrt = torch._foreach_sqrt(device_exp_avg_sqs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 8.00 GiB of which 0 bytes is free. Of the allocated memory 6.13 GiB is allocated by PyTorch, and 198.65 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

Process finished with exit code 1

Do you know how to solve this problem？

**Comment by G-walk** [comment]
I think it's normal the warning "Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration." shows up. I had the same warning and it didn't cause any problem to the program.

I think your problem was caused by other issues because your log shows "torch.OutOfMemoryError: CUDA out of memory. ".

Maybe your modifications to the code caused this problem, or it's because of multiGPU training.
